apiVersion: v1
kind: Service
metadata:
  name: invoice-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: invoice-backend
  ports:
    - port: 8000
      targetPort: 8000
      name: http
