apiVersion: apps/v1
kind: Deployment
metadata:
  name: invoice-frontend
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: invoice-frontend
  template:
    metadata:
      labels:
        app: invoice-frontend
    spec:
      containers:
        - name: invoice-frontend
          image: docker.io/{{ .Values.image.username }}/invoice-frontend:{{ .Values.image.frontendTag }}
          ports:
            - containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
