apiVersion: v1
kind: Service
metadata:
  name: invoice-postgres
  namespace: {{ .Values.namespace }}
spec:
  clusterIP: None
  selector:
    app: invoice-postgres
  ports:
    - port: 5432
      targetPort: 5432
      name: postgres
