apiVersion: v1
kind: Secret
metadata:
  name: invoice-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  database-url: >-
    postgresql://{{ .Values.postgres.user }}:{{ .Values.postgres.password }}@invoice-postgres:5432/{{ .Values.postgres.database }}
  postgres-password: {{ .Values.postgres.password | quote }}
  secret-key: {{ .Values.backend.secretKey | quote }}